# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MutableProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MutableProject
#私有库
pod 'PrivateVideoPlayer',:git=>'https://github.com/smithgoo/movesPlayer.git'

#公有库
pod 'AFNetworking'

end
